# Generated by Django 4.1.3 on 2022-11-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('1', 'Shoulders'), ('2', 'Chest'), ('3', 'Biceps'), ('4', 'Back'), ('5', 'Belly')], default='1', max_length=2),
        ),
    ]
