# Generated by Django 4.1.3 on 2022-11-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0002_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('Shoulders', 'Shoulder'), ('Chest', 'Chest'), ('Biceps', 'Biceps'), ('Back', 'Back'), ('Belly', 'Belly')], default='Shoulders', max_length=100),
        ),
    ]
