# Generated by Django 4.1.3 on 2022-11-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0003_alter_activity_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalactivity',
            name='seat_setting',
        ),
        migrations.AddField(
            model_name='activity',
            name='seat_setting',
            field=models.IntegerField(default=1),
        ),
    ]
