# Generated by Django 4.1.3 on 2022-11-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0005_activity_other_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='other_settings',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='activity',
            name='seat_setting',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
